name: build_test

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    
env:
  MONGODB_URI:  ${{ secrets.MONGODB_URI }}
  PORT:  ${{ secrets.PORT }}
  TEST_MONGODB_URI:  ${{ secrets.TEST_MONGODB_URI }} 
  SECRET: ${{ secrets.SECRET }}

jobs:

  test_bloglist_frontend_build:
    
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
        with:
          variableNames: MONGODB_URI, PORT, TEST_MONBODB_URI, SECRET 
     
      - name: npm install 
        run: npm install  
  
     # - name: build
     #   run: npm run build
        
     # - name: test frontend
     #  run: npm run test_frontend
      
      - name: test backend
        run: npm run test_backend
    
